### ISSUE TITLE
i tried the code.. and its not working

### ISSUE THREAD

**Issue by chizla** [cyberhck/fbchat#3]
checked and my server is open port 22 so i dont think it's issue with the server.
please advice.
im looking for solution to send messages to multiple friends via php

**Comment by chizla** [comment]
welcome emailHi cyberhck/fbchat,I am raising cash for a Vetinary loan through you and Lenderly. I need to borrow $600.00. You can lend or vouch for me - anything from $50 and up. I will pay it back over 4 months and I am offering collateral for you to choose from if I don’t pay you back on time.Please check out my link  and help me out Click herewww.Lenderly.co is helping me raise the cash and repay it.Thanks,davidLenderly(This message was sent by the Lenderly team on behalf of . Lenderly is a social lending platform based out of Miami Florida)

**Comment by cyberhck** [comment]
True
